name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  # Backend Tests and Build
  backend:
    name: Backend CI/CD
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check for security vulnerabilities
        run: npm audit --audit-level=high
        continue-on-error: true

      - name: Lint code
        run: |
          if [ -f "package.json" ] && grep -q "eslint" package.json; then
            npm run lint
          else
            echo "No linting script found, skipping..."
          fi
        continue-on-error: true

      - name: Run tests
        run: |
          if [ -f "package.json" ] && grep -q "test" package.json; then
            npm test
          else
            echo "No test script found, skipping..."
          fi
        continue-on-error: true

      - name: Build application
        run: |
          if [ -f "package.json" ] && grep -q "build" package.json; then
            npm run build
          else
            echo "No build script found, skipping..."
          fi
        continue-on-error: true

  # Frontend Tests and Build
  frontend:
    name: Frontend CI/CD
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check for security vulnerabilities
        run: npm audit --audit-level=high
        continue-on-error: true

      - name: Lint code
        run: |
          if [ -f "package.json" ] && grep -q "lint" package.json; then
            npm run lint
          else
            echo "No linting script found, skipping..."
          fi
        continue-on-error: true

      - name: Run tests
        run: |
          if [ -f "package.json" ] && grep -q "test" package.json; then
            npm test
          else
            echo "No test script found, skipping..."
          fi
        continue-on-error: true

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: frontend-build
          path: client/.next/
          retention-days: 7

  # Security and Quality Checks
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: [backend, frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
        continue-on-error: true

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
        continue-on-error: true
